# Generated by Django 3.1.4 on 2020-12-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinfo',
            name='paid',
            field=models.FloatField(),
        ),
    ]
