# Generated by Django 3.1.4 on 2020-12-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20201219_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceinfo',
            name='paid',
            field=models.FloatField(default=0),
        ),
    ]
