# Generated by Django 3.1.4 on 2020-12-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20201219_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompanyinfo',
            name='logo',
            field=models.ImageField(null=True, upload_to='Customer_company_logo'),
        ),
    ]
