# Generated by Django 3.1.4 on 2020-12-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20201226_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercompanyinfo',
            name='logo',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='Customer_company_logo'),
        ),
    ]
